name: 'backup-database'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/git-auto-commit-action@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Postgres15 
        run: |
          sudo apt-get remove postgresql-client-common
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
          sudo apt update
          sudo apt install postgresql-15 postgresql-client-15 -y
          /usr/lib/postgresql/15/bin/pg_dump --clean --if-exists --quote-all-identifiers --schema '*' --exclude-schema 'extensions|graphql|graphql_public|net|pgbouncer|pgsodium|pgsodium_masks|realtime|supabase_functions|storage|pg_*|information_schema' -d 'postgres://postgres.qpfpqzjzriwrmtnwawit:GhostAIA7713$$@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres'

